locale                   : "en-US"
title                    : "Lei Gu, Penn Engineering"
title_separator          : "-"
name                     : "Lei Gu"
description              : "Lei Gu and the Penn Power Electronics Research Lab develop power electronics and energy conversion systems for emerging technologies."
url                      : "https://leigupe.github.io"
baseurl                  : ""
repository               : "leigupe/leigupe.github.io"

author:
  name             : "Lei Gu"
  avatar           : "profile.png"
  bio              : "Assistant Professor, Penn Engineering | Visiting Academic, NVIDIA Research"
  location         : "Philadelphia, PA"
  googlescholar    : "https://scholar.google.com/citations?user=sJf1iI8AAAAJ&hl=en"
  email_display    : "leigu [at] engineering.upenn.edu"
  linkedin         : "leigusu"

include:
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

timezone: America/New_York

plugins:
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
